# For documentation on how to configure this file,
# see diesel.rs/guides/configuring-diesel-cli
# Gets created when we run : diesel setup
[print_schema]
file = "src/database/schema.rs"

import_types = ["crate::database::*", "diesel::sql_types::{Integer, Array, Text, Bool, Timestamp, Nullable, Uuid}",
    "super::Media_Enum_Map", "super::Location_Enum_Map", "super::MediaAudienceEnum",
    "diesel::sql_types::*", "diesel_geography::sql_types::*"]

# This is needed for the geographic ty4pes
#import_types = ["diesel::sql_types::*", "diesel_geography::sql_types::*"]
