{{- if .Values.useSecret -}}  # <1>

apiVersion: v1
kind: Secret      # <2>
metadata:
  name: {{ template "iot.fullname" . }}   # <3>
type: Opaque
data:
  client.crt: {{ printf "DevStuff" | b64enc }}  # <4>
  client.key: {{ printf "DevStuff" | b64enc }}
  root.ca: {{ printf "DevStuff" | b64enc }}
  databaseUrl: {{ printf "DevStuff" | b64enc }}
{{- end -}}